let SINGLE_FILE_OPTIONS = {
    removeHiddenElements: true,
    removeUnusedStyles: true,
    removeUnusedFonts: true,
    compressHTML: true,
    loadDeferredImages: true,
    loadDeferredImagesMaxIdleTime: 1500,
    filenameTemplate: "{page-title} ({date-locale} {time-locale}).html",
    infobarTemplate: "",
    filenameMaxLength: 192,
    filenameMaxLengthUnit: "bytes",
    filenameReplacedCharacters: ["~", "+", "\\\\", "?", "%", "*", ":", "|", "\"", "<", ">", "\x00-\x1f", "\x7F"],
    filenameReplacementCharacter: "_",
    removeAlternativeFonts: true,
    removeAlternativeMedias: true,
    removeAlternativeImages: true,
    groupDuplicateImages: true,
    maxSizeDuplicateImages: 512 * 1024,
    saveFavicon: true,
    insertMetaCSP: true,
    insertSingleFileComment: true,
    acceptHeaders: {
        font: "application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8",
        image: "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
        stylesheet: "text/css,*/*;q=0.1",
        script: "*/*",
        document: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        video: "video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5",
        audio: "audio/webm,audio/ogg,audio/wav,audio/*;q=0.9,application/ogg;q=0.7,video/*;q=0.6,*/*;q=0.5"
    },
    blockScripts: true,
    blockVideos: true,
    blockAudios: true
};